name: Android CI

on:
  push:
    branches: ["ci/cd"]
  pull_request:
    branches: ["ci/cd"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name : set Up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build App
        run: ./gradlew assembleDebug