name: Android CI

on:
  push:
    branches: [ "ci/cd" ]
  pull_request:
    branches: [ "ci/cd" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle and Cache
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build App
        run: ./gradlew build

  create_release:
    name: Create Signed APK
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'release.pks'
          encodedString: ${{ secrets.MY_RELEASE_KEYSTORE_BASE64 }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 2. Construye el APK de release firmado, usando las variables de entorno
      - name: Assemble Release APK
        run: ./gradlew :app:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.MY_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.MY_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.MY_KEYSTORE_PASSWORD }}
          SIGNING_STORE_FILE: ${{ steps.decode_keystore.outputs.filePath }}

      # 3. Sube el APK generado como un artefacto
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          # La ruta correcta al APK generado
          path: app/build/outputs/apk/release/app-release.apk
