name: Android CI

on:
  push:
    branches: [ "ci/cd" ]
  pull_request:
    branches: [ "ci/cd" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Es buena práctica darle nombre al primer paso también

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle and Cache
        uses: gradle/actions/setup-gradle@v3

      # Es una buena práctica dar permisos de ejecución al gradlew por si no los tuviera en Git
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build App
        run: ./gradlew assembleDebugleDebug